/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.calculator;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Restive Rakib
 */
public class Calculator extends javax.swing.JFrame {
    DateFormat dateformet = new SimpleDateFormat("dd/MM/YY");
    Date date=new Date();
  //  Calendar cal=Calendar.getInstance();
    

    /**
     * Creates new form Calculator
     */
    int check;
    private float k;
    private float l;
    private float r;
    private int count;
    public Calculator() {
        initComponents();
        check=0;
        count=0;
        datelbl.setText(" "+dateformet.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        tcgp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        scd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cadit = new javax.swing.JComboBox<>();
        gpa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ans = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(102, 255, 204));
        setPreferredSize(new java.awt.Dimension(850, 440));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3), "CGPA Calculator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 36), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 370));

        jButton1.setBackground(new java.awt.Color(255, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tcgp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tcgp.setForeground(new java.awt.Color(51, 51, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Credit: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("GPA: ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/example/calculator/Untitled.jpg"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(204, 0, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Final Result");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Sing out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Subject Code:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Result :");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cadit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1", "2", "3" }));

        gpa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gpa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "0.00", "2.00", "2.25", "2.50", "2.75", "3.00", "3.25", "3.50", "3.75", "4.00" }));
        gpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaActionPerformed(evt);
            }
        });

        ans.setAutoCreateRowSorter(true);
        ans.setBackground(new java.awt.Color(204, 255, 255));
        ans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Cadit", "Grade Point", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ans.setCellSelectionEnabled(false);
        ans.setEnabled(false);
        ans.setFocusable(false);
        ans.setOpaque(false);
        ans.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(ans);
        if (ans.getColumnModel().getColumnCount() > 0) {
            ans.getColumnModel().getColumn(0).setResizable(false);
            ans.getColumnModel().getColumn(1).setResizable(false);
            ans.getColumnModel().getColumn(2).setResizable(false);
            ans.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setText("Date:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(scd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tcgp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcgp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cadit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32))))
        );

        jMenu1.setText("Operation");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItem1.setText("Clear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("sign out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Final Result");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        Calculator n= new Calculator();
        n.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login n= new Login();
        n.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //first time add
        if(check==0){
            try {
                float  c=Float.parseFloat((String) cadit.getSelectedItem()); 
                 float g=Float.parseFloat((String) gpa.getSelectedItem()); 
        
                String  sc=scd.getText();
                
                 if (sc.length()==6 && sc.matches("[A-Z]*[0-9]+$")){
                     if(g==0)
                         count++;
                k=c*g;
                l=c;
                r=k/l;
                r=(float) (Math.round(r*100.0)/100.0);
                
                    tcgp.setText(null);
                     DefaultTableModel model=(DefaultTableModel) ans.getModel();
                     if(g==4)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"A+"});
                     else if(g<4&&g>=3.75)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"A"});
                     else if(g<3.75&&g>=3.50)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"A-"});
                     else if(g<3.50&&g>=3.25)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"B+"});
                     else if(g<3.25&&g>=3.00)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"B"});
                     else if(g<3.00&&g>=2.75)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"B-"});
                     else if(g<2.75&&g>=2.50)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"C+"});
                     else if(g<2.50&&g>=2.25)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"C"});
                     else if(g<2.25&&g>=2.00)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"D"});
                     else
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"F"});
                 scd.setText(null);
                 cadit.setSelectedItem("None");
                 gpa.setSelectedItem("None");
                 check++;
                    if (g==0.00){
                    JOptionPane.showMessageDialog(null,"Sorry , You Are Failed In This Subject");
          
                }
                else{
                        if(g==4.00)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  A+  Grade in this Subject");
                            else if(g<4.00&&g>=3.75)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  A  Grade in this Subject");
                            else if(g<3.75&&g>=3.50)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  A-  Grade in this Subject");
                            else if(g<3.50&&g>=3.25)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  B+  Grade in this Subject");
                            else if(g<3.25&&g>=3.00)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  B  Grade in this Subject");
                            else if(g<3.00&&g>=2.75)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  B-  Grade in this Subject");
                            else if(g<2.75&&g>=2.50)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  C+  Grade in this Subject");
                            else if(g<2.50&&g>=2.25)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  C  Grade in this Subject");
                            else if(g<2.25&&g>=2.00)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  D  Grade in this Subject");
                    }
                }
                 else{
                   JOptionPane.showMessageDialog(null,"Your Subject Code is not Right");
                 }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Please Give input for all fields");
            }
          
            }
        //first time add finished
        else{
            try {
                // float tm,tc,r;
                 float  c=Float.parseFloat((String) cadit.getSelectedItem()); 
                 float g=Float.parseFloat((String) gpa.getSelectedItem());
               
                String  sc=scd.getText();
                 if (sc.length()==6 && sc.matches("[A-Z]*[0-9]+$")){
                       if(g==0)
                            count++;
                 k+=(c*g);
                l+=c;
                r=k/l;
                r=(float) (Math.round(r*100.0)/100.0);
                    tcgp.setText(null);
                
                   DefaultTableModel model=(DefaultTableModel) ans.getModel();
                     if(g==4)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"A+"});
                     else if(g<4&&g>=3.75)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"A"});
                     else if(g<3.75&&g>=3.50)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"A-"});
                     else if(g<3.50&&g>=3.25)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"B+"});
                     else if(g<3.25&&g>=3.00)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"B"});
                     else if(g<3.00&&g>=2.75)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"B-"});
                     else if(g<2.75&&g>=2.50)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"C+"});
                     else if(g<2.50&&g>=2.25)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"C"});
                     else if(g<2.25&&g>=2.00)
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"D"});
                     else
                     model.addRow(new Object[]{scd.getText(),cadit.getSelectedItem(),gpa.getSelectedItem(),"F"});
                 scd.setText(null);
                 cadit.setSelectedItem("None");
                 gpa.setSelectedItem("None");
                 check++;
                
                    if (g==0.00){
                    JOptionPane.showMessageDialog(null,"Sorry , You Are Failed In This Subject");
          
                }
                else{
                       if(g==4.00)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  A+  Grade in this Subject");
                            else if(g<4.00&&g>=3.75)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got A Grade in this Subject");
                            else if(g<3.75&&g>=3.50)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  A-  Grade in this Subject");
                            else if(g<3.50&&g>=3.25)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  B+  Grade in this Subject");
                            else if(g<3.25&&g>=3.00)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  B  Grade in this Subject");
                            else if(g<3.00&&g>=2.75)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  B-  Grade in this Subject");
                            else if(g<2.75&&g>=2.50)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  C+  Grade in this Subject");
                            else if(g<2.50&&g>=2.25)
                    JOptionPane.showMessageDialog(null,"You have Passed in this Subject\n You Got  C  Grade in this Subject");
                            else if(g<2.25&&g>=2.00)
                    JOptionPane.showMessageDialog(null,"You have Passed in This Subject\n You Got  D  Grade in this Subject");
 
                     }
                 }
                 else{
                   JOptionPane.showMessageDialog(null,"Your Subject Code is not Right"); 
            }
            }
             catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Please Give input for all fields");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Calculator n= new Calculator();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Login n= new Login();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           if(l!=0){
                if(count==0){
                 tcgp.setText("CGPA: "+r);
                }else{
                    tcgp.setText("Fail");
                }
               if(count==0){
                   
                if(r==4.00)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  A+  Grade & Your Grade Point is "+r);
                else if(r<4.0&&r>=3.75)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  A  Grade & Your Grade Point is "+r);
                else if(r<3.75&&r>=3.50)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  A-  Grade & Your Grade Point is "+r);
                else if(r<3.50&&r>=3.25)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  B+  Grade & Your Grade Point is "+r);
                else if(r<3.25&&r>=3.00)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  B  Grade & Your Grade Point is "+r);
                else if(r<3.00&&r>=2.75)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  B-  Grade & Your Grade Point is "+r);
                else if(r<2.75&&r>=2.50)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  C+  Grade & Your Grade Point is "+r);
                 else if(r<2.50&&r>=2.25)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  C  Grade & Your Grade Point is "+r);
                 else if(r<2.25&&r>=2.00)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  D  Grade & Your Grade Point is "+r);
               }
               else 
               {
                   if(count==1){
                       if(check==1)
                           JOptionPane.showMessageDialog(null,"You have Failed in "+count+" out of "+check+" Subject.\n Please Improve This Subject Then Your Result Can be Shown.");
                       else
                           JOptionPane.showMessageDialog(null,"You have Failed in "+count+" out of "+check+" Subjects.\n Please Improve This Subject Then Your Result Can be Shown.");
                       
                   }
                       
               else
                       JOptionPane.showMessageDialog(null,"You have Failed in "+count+" out of "+check+" Subjects.\n Please Improve These Subjects Then Your Result Can be Shown.");
               }
           }
        else
               JOptionPane.showMessageDialog(null,"You didn't put anydata.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        about a=new about();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here
        if(l!=0){
                if(count==0){
                 tcgp.setText("CGPA: "+r);
                }else{
                    tcgp.setText("Fail");
                }
               if(count==0){
                   
                if(r==4.00)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  A+  Grade & Your Grade Point is "+r);
                else if(r<4.0&&r>=3.75)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  A  Grade & Your Grade Point is "+r);
                else if(r<3.75&&r>=3.50)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  A-  Grade & Your Grade Point is "+r);
                else if(r<3.50&&r>=3.25)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  B+  Grade & Your Grade Point is "+r);
                else if(r<3.25&&r>=3.00)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  B  Grade & Your Grade Point is "+r);
                else if(r<3.00&&r>=2.75)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  B-  Grade & Your Grade Point is "+r);
                else if(r<2.75&&r>=2.50)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  C+  Grade & Your Grade Point is "+r);
                 else if(r<2.50&&r>=2.25)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  C  Grade & Your Grade Point is "+r);
                 else if(r<2.25&&r>=2.00)
                       JOptionPane.showMessageDialog(null,"Congratulation !!\n You have Passed All Subjects\n You Got  D  Grade & Your Grade Point is "+r);
               }
               else 
               {
                   if(count==1){
                       if(check==1)
                           JOptionPane.showMessageDialog(null,"You have Failed in "+count+" out of "+check+" Subject\n Please Improve This Subject Then Your Result Can be Shown");
                       else
                           JOptionPane.showMessageDialog(null,"You have Failed in "+count+" out of "+check+" Subjects\n Please Improve This Subject Then Your Result Can be Shown");
                       
                   }
                       
               else
                       JOptionPane.showMessageDialog(null,"You have Failed in "+count+" out of "+check+" Subjects\n Please Improve These Subjects Then Your Result Can be Shown");
               }
           }
        else
               JOptionPane.showMessageDialog(null,"You didn't put anydata");
    
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ans;
    private javax.swing.JComboBox<String> cadit;
    private javax.swing.JLabel datelbl;
    private javax.swing.JComboBox<String> gpa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField scd;
    private javax.swing.JLabel tcgp;
    // End of variables declaration//GEN-END:variables
}
